version: 2
references:
  nodejs: &nodejs
    docker:
      - image: circleci/node:8.9
    working_directory: ~/repo

jobs:
  build:
    <<: *nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install --fronzen-lockfile
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn/
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: "Build"
          command: |
            yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*

  test:
    <<: *nodejs
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: "Lint"
          command: yarn lint src/
      - run:
          name: "Test"
          command: yarn test

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
